-- MySQL Script generated by MySQL Workbench
-- Fri Oct 14 00:18:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `default` TINYINT(1) NULL DEFAULT NULL,
  `permissions` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `is_confirmed` TINYINT(1) NULL DEFAULT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `role_id` INT NULL DEFAULT NULL,
  `token` VARCHAR(1000) NULL DEFAULT NULL,
  `online` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `about_me` TEXT NULL DEFAULT NULL,
  `passlen` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `Role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `Role`
    FOREIGN KEY (`role_id`)
    REFERENCES `db`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `article_name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `Autor_idx` (`author_id` ASC) VISIBLE,
  UNIQUE INDEX `article_name_UNIQUE` (`article_name` ASC) VISIBLE,
  CONSTRAINT `Author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `db`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
