"""empty message

Revision ID: e144cdc22572
Revises: e97123e8ae9d
Create Date: 2022-10-26 13:35:05.925596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e144cdc22572'
down_revision = 'e97123e8ae9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'heading',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('Autor_idx', table_name='articles')
    op.drop_index('article_name_UNIQUE', table_name='articles')
    op.drop_index('article_position_UNIQUE', table_name='articles')
    op.drop_index('cover_path_UNIQUE', table_name='articles')
    op.drop_index('path_UNIQUE', table_name='articles')
    op.drop_constraint('Author_id', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    op.alter_column('comments', 'users_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'articles_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('fk_comments_articles1_idx', table_name='comments')
    op.drop_index('fk_comments_users1_idx', table_name='comments')
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.drop_constraint('Article', 'comments', type_='foreignkey')
    op.drop_constraint('User', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'articles', ['articles_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['users_id'], ['id'])
    op.alter_column('roles', 'login',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('roles', 'permissions',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.drop_index('fk_userarticle_users1_idx', table_name='user_art_attitude')
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('users', 'hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index('Role_idx', table_name='users')
    op.drop_index('fk_users_articles1_idx', table_name='users')
    op.create_unique_constraint(None, 'users', ['token'])
    op.drop_constraint('Role', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'dislike_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dislike_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('Role', 'users', 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('fk_users_articles1_idx', 'users', ['dislike_id'], unique=False)
    op.create_index('Role_idx', 'users', ['role_id'], unique=False)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.create_index('fk_userarticle_users1_idx', 'user_art_attitude', ['users_id'], unique=False)
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.alter_column('roles', 'permissions',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'login',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('User', 'comments', 'users', ['users_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('Article', 'comments', 'articles', ['articles_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.create_index('fk_comments_users1_idx', 'comments', ['users_id'], unique=False)
    op.create_index('fk_comments_articles1_idx', 'comments', ['articles_id'], unique=False)
    op.alter_column('comments', 'articles_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'users_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('Author_id', 'articles', 'users', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('path_UNIQUE', 'articles', ['path'], unique=False)
    op.create_index('cover_path_UNIQUE', 'articles', ['cover_path'], unique=False)
    op.create_index('article_position_UNIQUE', 'articles', ['article_position'], unique=False)
    op.create_index('article_name_UNIQUE', 'articles', ['article_name'], unique=False)
    op.create_index('Autor_idx', 'articles', ['author_id'], unique=False)
    op.alter_column('articles', 'heading',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
