"""empty message

Revision ID: e97123e8ae9d
Revises: 
Create Date: 2022-10-15 22:44:58.525440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e97123e8ae9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Autor_idx', table_name='articles')
    op.drop_index('article_name_UNIQUE', table_name='articles')
    op.drop_constraint('Author_id', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    op.alter_column('roles', 'login',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('roles', 'permissions',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('users', 'hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index('Role_idx', table_name='users')
    op.create_unique_constraint(None, 'users', ['token'])
    op.drop_constraint('Role', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'passlen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passlen', mysql.VARCHAR(length=45), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('Role', 'users', 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('Role_idx', 'users', ['role_id'], unique=False)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('users', 'login',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.alter_column('roles', 'permissions',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'login',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('Author_id', 'articles', 'users', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('article_name_UNIQUE', 'articles', ['article_name'], unique=False)
    op.create_index('Autor_idx', 'articles', ['author_id'], unique=False)
    # ### end Alembic commands ###
